macuos/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.http import HttpResponse
from.import views
import logging 

logging.getLogger('command').debug(' >>> ' + __name__)

urlpatterns = [ 
    # 2018/08/16 M00002 s-hama>>>
    #url(r'^', views.PostIndexView.as_view(), name='index'),
    path('', views.PostIndexView.as_view(), name='index'), 
    # 2018/08/16 M00002 s-hama <<<

    url(r'^detail/(?P<pk>[0-9]+)/$',
        views.PostDetailView.as_view(), name='detail'),
 
    url(r'^category/(?P<big>\w+)/(?P<small>\w+)/$',
        views.CategoryView.as_view(), name='category'),
 
    url(r'^category/(?P<big>\w+)/$',
        views.CategoryView.as_view(), name='category'),
 
    url(r'^tag/(?P<tag>\w+)/$', 
        views.TagView.as_view(), name='tag'),

    url(r'^profile/$',
        views.ProfileView.as_view(), name='profile'),

    url(r'^contact/$',
        views.ContactView.as_view(), name='contact'),

    url(r'^ppolicy/$',
        views.PpolicyView.as_view(), name='ppolicy'),

    url(r'^ads.txt',
	lambda x: HttpResponse('google.com, pub-4029756773390765, DIRECT, f08c47fec0942fa0', content_type='text/plain'), name='adsfile'),
]

macuos/models.py
from django.db import models
 
 
def _get_latest_post(queryset):
    """もらったクエリセットを、さらに絞り込んで返す。"""
 
    return queryset.filter(is_publick=True).order_by('-created_at')[:5]
 
 
class BigCategory(models.Model):
    """大カテゴリ"""
 
    name = models.CharField("大カテゴリ名", max_length=255)
    created_at = models.DateTimeField("作成日", auto_now_add=True)
 
    def __str__(self):
        return self.name
 
    def get_latest_post(self):
        queryset = Post.objects.filter(category__parent=self)
        return _get_latest_post(queryset)
 
 
class SmallCategory(models.Model):
    """小カテゴリー"""
 
    name = models.CharField("小カテゴリ名", max_length=255)
    parent = models.ForeignKey(BigCategory, verbose_name="大カテゴリ", on_delete=models.CASCADE)
    created_at = models.DateTimeField("作成日", auto_now_add=True)
 
    def __str__(self):
        return self.name
 
    def get_latest_post(self):
        queryset = Post.objects.filter(category=self)
        return _get_latest_post(queryset)
 
 
class Tag(models.Model):
    """タグ"""
 
    name = models.CharField("タグ名", max_length=255)
    created_at = models.DateTimeField("作成日", auto_now_add=True)
 
    def __str__(self):
        return self.name
 
    def get_latest_post(self):
        queryset = Post.objects.filter(tag=self)
        return _get_latest_post(queryset)
 
 
class Post(models.Model):
    """ブログのポスト"""
 
    title = models.CharField("タイトル", max_length=255)
    text = models.TextField("本文")
    category = models.ForeignKey(SmallCategory, verbose_name="カテゴリ", on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="タグ")
    thumbnail = models.ImageField("サムネイル", upload_to='thumbnail/', blank=True)
    is_publick = models.BooleanField("公開可能か?", default=True)
    is_html = models.BooleanField("HTMLソースか?", default=False)
    created_at = models.DateTimeField("作成日", auto_now_add=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)
 
    def __str__(self):
        return self.title

macuos/views.py
from django.urls import reverse_lazy
from django.db.models import Q
from django.views import generic
from .models import Post
#import concurrent.futures
#import multiprocessing
#from multiprocessing import Process
import logging
#import sys
 
class BaseListView(generic.ListView):
    paginate_by = 10 
    def base_queryset(self):
        queryset = Post.objects.filter(
            is_publick=True).order_by('-created_at')
        logging.getLogger('command').debug('ON View.py > BaseListView')
        return queryset
 
class PostIndexView(BaseListView):
    def get_queryset(self):
        queryset = self.base_queryset()
        keyword = self.request.GET.get("quick")
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword))
        logging.getLogger('command').debug('ON View.py > PostIndexView')
        return queryset

class CategoryView(BaseListView):
    def get_queryset(self):
        queryset = self.base_queryset()
        category = self.kwargs.get("small")
        if category:
            queryset = queryset.filter(category__name=category)
        else:
            category = self.kwargs.get("big")
            queryset = queryset.filter(category__parent__name=category)
        logging.getLogger('command').debug('ON View.py > CategoryView')
        return queryset
 
 
class TagView(BaseListView):
    def get_queryset(self):
        tag = self.kwargs["tag"]
        queryset = self.base_queryset().filter(tag__name=tag)
        logging.getLogger('command').debug('ON View.py > TagView')
        return queryset
 
class ProfileView(BaseListView):
    def get_queryset(self):
        queryset = self.base_queryset()
        return queryset

class ContactView(BaseListView):
    def get_queryset(self):
        queryset = self.base_queryset()
        return queryset

class PpolicyView(BaseListView):
    def get_queryset(self):
        queryset = self.base_queryset()
        return queryset

class PostDetailView(generic.DetailView):
    model = Post
    # 2018/08/16 add hama >>> 
    def get_object(self, queryset=None):
        post = super().get_object()
        # M00008 2021/11/03 mod hama >>>
        logging.getLogger('command').debug(post.category)
        # 小カテゴリー名にPaidContentが含まれていない場合は、公開中であれば表示。
        # 小カテゴリー名にPaidContentが含まれている場合はは、公開中かつ、ログイン承認済である場合のみ表示。
        # 上記以外は、404エラーを表示。
        if str(post.category) not in str("PaidContent") and post.is_publick:
            return post
        elif str(post.category) in str("PaidContent") and post.is_publick and self.request.user.is_authenticated:
            return post
        else:
            raise Http404
        # <<<
    # <<<

macuos/templates/macuos/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Menu -->
    <meta name="msapplication-config" content="{% static 'macuos/img/fav/browserconfig.xml'  %}" />
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'macuos/img/fav/mstile-144x144.png'  %}">
    <meta name="theme-color" content="#f5deb3">
    <link rel="icon" type="image/x-icon" href="{% static 'macuos/img/fav/favicon.png'  %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'macuos/img/fav/apple-touch-icon-180x180.png'  %}">
    <link rel="mask-icon" href="./safari-icon.svg" color="#555" />
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'macuos/img/fav/android-chrome-192x192.png'  %}">
    <!--<link rel="manifest" href="https://unisia-se.jp/img/fav/manifest.json">-->

    <!-- Src Disp : highlight Var 9.13.0-->
    <link rel="stylesheet" href="{% static 'macuos/a11y-dark.css'  %}">
    <script src="{% static 'macuos/highlight.pack.js'  %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <!-- SNS Other -->
    <meta property="og:url"           content="https://unisia-se.com" />
    <meta property="og:type"          content="article" />
    <meta property="og:title"         content="UNISIA-SE Tech Blog" />
    <meta property="og:description"   content="Engineer Tech Blog" />
    <meta property="og:image"         content="{% static 'macuos/img/UNISIA-SE2.jpg'  %}" />
    <meta property="author"         content="UNISIA-SE Tech Blog" />
    <!-- SNS Buttom-->
    <link rel="stylesheet" href="{% static 'macuos/sns-icon.css'  %}">
    <link rel="stylesheet" href="{% static 'macuos/sns-style.css'  %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,900">
    <link rel="stylesheet" href="{% static 'macuos/icomoon.eot'  %}">
    <link rel="stylesheet" href="{% static 'macuos/icomoon.svg'  %}">
    <link rel="stylesheet" href="{% static 'macuos/icomoon.ttf'  %}">
    <link rel="stylesheet" href="{% static 'macuos/icomoon.woff'  %}">

    <!-- Code Google run prettify -->
    <!--<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>-->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125872348-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-125872348-3');
    </script>

    <!-- MathJax -->
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'macuos/base.css'  %}">

    <!-- Google AdSense MAIN-->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
     (adsbygoogle = window.adsbygoogle || []).push({
       google_ad_client: "ca-pub-4029756773390765",
       enable_page_level_ads: true
     });
    </script>
    <!-- Google AdSense AMP-->
    <script async custom-element="amp-auto-ads"
        src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
    </script>
  </head>
  <body>
    <!-- Google AdSense AMP-->
    <amp-auto-ads type="adsense"
       data-ad-client="ca-pub-4029756773390765">
    </amp-auto-ads>
    <!-- facebook -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v3.2'
        fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
    </script>
    <nav class="navbar navbar-dark bg-primary" style="border-radius:.1rem">
      <button class="navbar-toggler hidden-sm-up" style = "color: #ffffff; border-color: #ffffff" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
        Menu
      </button>
      <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
        <div class="container">
          <a class="navbar-brand" href="https://unisia-se.com">
		  <img src="{% static 'macuos/img/unisia_mark_h.png'  %}" width="30" height="30"  style="float:left; margin-right:5px;" alt="UNISIA-SE">
          </a>
          <ul class="nav navbar-nav">
            <li class="nav-item {% block nav_home %}{% endblock %}">
              <a class="nav-link" href="{% url 'macuos:index' %}">BlogTop<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'macuos:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'macuos:contact' %}">Contact</a>
            </li>
	    <!--
            <li class="nav-item">
              <a class="nav-link" href="https://unisia-se.jp">HP</a>
            </li>
            -->
            <li class="nav-item">
              <a class="nav-link" href="{% url 'macuos:ppolicy' %}">PrivacyPolicy</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
            {% endif %}
          </ul>
          <form action="{% url 'macuos:index' %}" method="GET" class="form-inline pull-xs-right">
            <input class="form-control" type="text" name="quick" style="width:160px" placeholder="キーワードを入力">
            <button class="btn btn-outline-success" type="submit">検索</button>
          </form>
        </div>
      </div>
    </nav>
 
    <div class="jumbotron" style="padding:2rem 1rem;background-color: #3c3c3c;border-radius:.1rem">
      <div class="container" style="background-size:260px 130px;">
        <h1 style="color:#f5f5f5;text-align:left;">UNISIA-SE Tech Blog</h2>
        <p class="lead text-muted" style="text-align:left;">
            <small>ダメンジニアの気まぐれお勉強日記</small>
        </p>
        <a href="https://px.a8.net/svt/ejp?a8mat=3NN1YJ+3JES8I+50+2HN8K1" rel="nofollow">
         <img border="0" width="728" height="90" alt="" src="https://www28.a8.net/svt/bgt?aid=221105323214&wid=001&eno=01&mid=s00000000018015057000&mc=1"></a>
        <img border="0" width="1" height="1" src="https://www16.a8.net/0.gif?a8mat=3NN1YJ+3JES8I+50+2HN8K1" alt="">
      </div>
      <img border="0" width="1" height="1" src="https://www16.a8.net/0.gif?a8mat=3NN1YJ+3JES8I+50+2HN8K1" alt="">
    </div>
 
    <div class="container">
      <div class="row">
	  <div class="col-xs-12 col-sm-9">
          {% if request.path == '/profile/' %}
            {% include "macuos/profile.html" %}
          {% elif request.path == '/contact/' %}
            {% include "macuos/contact.html" %}
          {% elif request.path == '/ppolicy/' %}
            {% include "macuos/ppolicy.html" %}
          {% else %}
            {% block content %}{% endblock %}
          {% endif %}
        </div>
	<div class="col-xs-12 col-sm-3">
          {% include "macuos/side.html" %}
        </div>
      </div>
    </div>
    <div class="bg-primary" style="margin-top:20px;">
      <div class="container" style="text-align:center;padding-top:10px;padding-bottom:10px;">
        <div class="text-white">Copyright UNISIA-SE All Rights Reserved.</div>
        <div><a style="color:#ffffff;" href="mailto:s-hama@unisia-se.jp" rel="nofollow">s-hama@unisia-se.jp</a></div>
      </div>
    </div>
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <!-- Custom JS -->
    <!--<script src="{% static 'macuos/js/base.js' %}"></script>-->
  </body>
</html>

macuos/templates/macuos/contact.html
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <h3 style="color:Navy;text-align:left;">Contact</h3>
      <p class="lead text-muted" style="text-align:left;">
        <small>
          本サイトについてのご意見・ご感想などをお寄せください。<br /><br />
          お問い合わせの際は、お手数ですが下記メールアドレスへお願い致します。<br />
          　s-hama@unisia-se.jp<br /><br />
          回答には時間を要する場合がありますので、予めご了承ください。<br />
          
        </small>
      </p>
    </div>
  </div>
</div>

macuos/templates/macuos/latest_post.html
<div class="row">
  <div class="col-xs-12 col-sm-12">
    「{{ post.category.parent.name }}」の最新 5件<br>
    {% for latest in post.category.parent.get_latest_post %}
      ・<a href="{% url 'macuos:detail' latest.pk %}">{{ latest.title }}</a><br>
    {% endfor %}
  </div>
 
  <!--
  <div class="col-xs-12 col-sm-6 m-t-1">
    「{{ post.category.name }}」の最新5件<br>
    {% for latest in post.category.get_latest_post %}
      <a href="{% url 'macuos:detail' latest.pk %}">{{ latest.title }}</a><br>
    {% endfor %}
  </div>
  -->
  <!--
   {% for tag in post.tag.all %}
    <div class="col-xs-12 col-sm-6 m-t-1">
      「{{ tag.name }}」の最新5件<br>
      {% for latest in tag.get_latest_post %}
        <a href="{% url 'macuos:detail' latest.pk %}">{{ latest.title }}</a><br>  
      {% endfor %}
    </div>
  {% endfor %}
  -->     
</div>
<br />

macuos/templates/macuos/page.html
{% load page %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

macuos/templates/macuos/post_detail.html
{% extends "macuos/base.html" %}
{% block content %}
<div class="card card-outline-primary">
  <div class="card-header bg-primary">
    <!-- <h1 class="card-title">{{ post.title }}</h1> -->
    <h4>{{ post.title }}</h4>
  </div>
 
  <div class="card-block">
    {% if post.is_html %}
      {{ post.text | safe}}
    {% else %}
      {{ post.text | urlize | linebreaks }}
    {% endif %}
    
    <hr>
    {% include "macuos/latest_post.html" %}
  </div>
 
  <div class="card-footer">
	  <span class="tag tag-info">{{ post.category.parent }}</span>
	  <span class="tag tag-primary">{{ post.category }}</span>
	  {% for tag in post.tag.all %}
	    <span class="tag tag-success">{{ tag.name }}</span>
	  {% endfor %}
	  <p class="text-muted">{{ post.created_at }}</p>
    {% if user.is_authenticated %}
      <p><a class="nav-link" href="{% url 'admin:macuos_post_change' post.pk %}">管理画面へ</a></p>
    {% endif %}
  </div>
</div>
{% endblock %}

macuos/templates/macuos/post_list.html
{% extends "macuos/base.html" %}
{% load static %}
{% block nav_home %}active{% endblock %}
{% block content %}
<ul class="shareList">
  <li class="shareList__item"><a class="shareList__link icon-twitter" href="http://twitter.com/share?url=https://unisia-se.com" target="_blank" title="Twitter"></a></li>
  <li class="shareList__item"><a class="shareList__link icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u=https://unisia-se.com" target="_blank" title="Facebook"></a></li>
  <li class="shareList__item"><a class="shareList__link icon-hatebu" href="http://b.hatena.ne.jp/add?mode=confirm&url=https://unisia-se.com" target="_blank" title="はてなブックマーク"></a></li>
  <li class="shareList__item"><a class="shareList__link icon-pocket" href="http://getpocket.com/edit?url=https://unisia-se.com" target="_blank" title="Pocket"></a></li>
  <li class="shareList__item"><a class="shareList__link icon-feedly" href="https://feedly.com/i/subscription/feed/https://unisia-se.com" target="_blank" title="Feedly"></a></li>
  <li class="shareList__item"><a class="shareList__link icon-line" href="http://line.me/R/msg/text/?https://unisia-se.com" target="_blank" title="LINE"></a></li>
</ul>
<br />
  {% for post in post_list %}
    <div class="row m-b-3">
      <!-- 2018/08/15 M000001 s-hama >>> -->
      <!--
      <div class="col-xs-12 col-sm-6 text-xs-center">	
        {% if post.thumbnail %}	
          <img class="img-thumbnail" src="{{ post.thumbnail.url }}">	
        {% else %}	
          <img class="img-thumbnail" src="{% static 'macuos/img/noimage.png' %}">	
        {% endif %}	
      </div>
      -->
      <!-- 2018/08/15 M00001 s-hama <<<  -->
      <!-- 2018/08/15 M00001 s-hama >>>
      <!--<div class="col-xs-12 col-sm-6"> -->
      <div class="col-xs-12 col-sm-12">
      <!-- 2018/08/15 M00001 s-hama <<< -->
        <h4>{{ post.title }}</h4>
        <span class="tag tag-info">{{ post.category.parent }}</span>
        <span class="tag tag-primary">{{ post.category }}</span>
        {% for tag in post.tag.all %}
          <span class="tag tag-success">{{ tag.name }}</span>
        {% endfor %}
        <p class="text-muted">{{ post.created_at }}</p>
        {% if user.is_authenticated %}
        <p>
	<a class="nav-link" href="{% url 'admin:macuos_post_change' post.pk %}">>> To Management</a>
        </p>
        {% endif %}
	<a class="btn btn-outline-primary btn-lg btn-block" href="{% url 'macuos:detail' post.pk %}">>> Read More</a>
      </div>
    </div>
  {% endfor %}
  <ul class="shareList">
    <li class="shareList__item"><a class="shareList__link icon-twitter" href="http://twitter.com/share?url=https://unisia-se.com" target="_blank" title="Twitter"></a></li>
    <li class="shareList__item"><a class="shareList__link icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u=https://unisia-se.com" target="_blank" title="Facebook"></a></li>
    <li class="shareList__item"><a class="shareList__link icon-hatebu" href="http://b.hatena.ne.jp/add?mode=confirm&url=https://unisia-se.com" target="_blank" title="はてなブックマーク"></a></li>
    <li class="shareList__item"><a class="shareList__link icon-pocket" href="http://getpocket.com/edit?url=https://unisia-se.com" target="_blank" title="Pocket"></a></li>
    <li class="shareList__item"><a class="shareList__link icon-feedly" href="https://feedly.com/i/subscription/feed/https://unisia-se.com" target="_blank" title="Feedly"></a></li>
    <li class="shareList__item"><a class="shareList__link icon-line" href="http://line.me/R/msg/text/?https://unisia-se.com" target="_blank" title="LINE"></a></li>
  </ul>
  <div class="text-xs-center">
    {% include "macuos/page.html" %}
  </div>
{% endblock %}

macuos/templates/macuos/side.html
 <div class="list-group">
  <!-- 2018/08/16 M00005 s-hama >>> -->
  <a href="#" class="list-group-item active text-xs-left">
    Categories
  </a>

  <!-- 2018/08/16 M00005 s-hama <<< -->
  {% for big in big_categories %}
  <!-- 2018/08/16 M00005 s-hama >>> -->
  <a class="list-group-item" data-toggle="collapse" href="#c-{{ big.pk }}" aria-expanded="false" aria-controls="c-{{ big.pk }}">
    {{ big.name }}
  </a>
  <!-- 2018/08/16 M00005 s-hama <<< -->
  <div class="collapse" id="c-{{ big.pk }}">
    <!-- 2018/08/16 M00005 s-hama >>> -->
    <a href="{% url 'macuos:category' big.name %}" class="list-group-item">
      &nbsp;>&nbsp;{{ big.name }}
    </a>
    <!-- 2018/08/16 M00005 s-hama <<< -->

    {% for small in big.smallcategory_set.all %}
    <a href="{% url 'macuos:category' big.name small.name %}" class="list-group-item">
      &nbsp;>>&nbsp;{{ small.name }}
    </a>
    {% endfor %}

  </div>
  {% endfor %}
</div>

<!-- 2018/08/16 M00006 s-hama >>> -->
<br />
<div class="list-group mt-5">
  <a href="#" class="list-group-item active text-xs-left">
    Tags
  </a>
  {% for tag in tags  %}
  <a class="list-group-item" href="{% url 'macuos:tag' tag.name %}">
      {{ tag.name }}
  </a>
  {% endfor %}
</div>
<!-- 2018/08/16 M00006 s-hama <<< --> 